### ISSUE TITLE
Set up redirects from the old RTD website

### ISSUE THREAD

**Issue by webknjaz** [pypa/build#171]
https://github.com/FFY00/python-build still links to https://python-build.readthedocs.io/ in the repo settings (sidebar).
I'm pretty sure that there's many places on the Internet that do so too.
Plus somebody probably has it bookmarked and browsers usually autocomplete previously visited URLs.

I propose configuring redirects from the old URL to the new one.

**Comment by FFY00** [comment]
I have added a notice in the description that that repo is my personal development fork and have changed the url from the old documentation to this repo.

**Comment by FFY00** [comment]
I think I've addressed the issue, but feel free to reopen if not :blush:

**Comment by webknjaz** [comment]
https://python-build.readthedocs.io/ still doesn't have redirects to the new location

**Comment by FFY00** [comment]
Ah, sorry, I see.

**Comment by FFY00** [comment]
Should be good now.

**Comment by webknjaz** [comment]
Great, it works!
